services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes: 
            - ./dbinit/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:3307
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: abcd
      MYSQL_ROOT_PASSWORD: abcd
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mysqldb
      DB_USER: 'root'
      DB_PASSWORD: 'abcd'
      DB_NAME: patientsdb
      DB_PORT: 3307
      DB_CONNECTION_LIMIT: 10
      SERVER_PORT: 3000
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge